In [2]:
import pandas as pd

In [3]:
url = "https://raw.githubusercontent.com/4GeeksAcademy/regularized-linear-regression-project-tutorial/main/demographic_health_data.csv"

df = pd.read_csv(url)
df.to_csv("/workspaces/EDA_4/data/raw/demographic_health_data.csv")

print(df.columns)

Index(['fips', 'TOT_POP', '0-9', '0-9 y/o % of total pop', '19-Oct',
       '10-19 y/o % of total pop', '20-29', '20-29 y/o % of total pop',
       '30-39', '30-39 y/o % of total pop',
       ...
       'COPD_number', 'diabetes_prevalence', 'diabetes_Lower 95% CI',
       'diabetes_Upper 95% CI', 'diabetes_number', 'CKD_prevalence',
       'CKD_Lower 95% CI', 'CKD_Upper 95% CI', 'CKD_number',
       'Urban_rural_code'],
      dtype='object', length=108)

In [4]:
valores_nulos = df.isnull().sum()
valores_nulos.to_csv("/workspaces/EDA_4/data/interim/nulls.csv")

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3140 entries, 0 to 3139
Columns: 108 entries, fips to Urban_rural_code
dtypes: float64(61), int64(45), object(2)
memory usage: 2.6+ MB

In [6]:
len(df.drop_duplicates().sum())

columns = ["Median_Household_Income_2018", "Percent of Population Aged 60+", "STATE_NAME", "anycondition_prevalence", "Obesity_prevalence", "Heart disease_prevalence",  "COPD_prevalence", "diabetes_prevalence", "CKD_prevalence"]

In [7]:
total_data = df[columns]
total_data

,Median_Household_Income_2018,Percent of Population Aged 60+,STATE_NAME,anycondition_prevalence,Obesity_prevalence,Heart disease_prevalence,COPD_prevalence,diabetes_prevalence,CKD_prevalence
0,59338,19.1,Alabama,47.6,35.8,7.9,8.6,12.9,3.1
1,57588,26.3,Alabama,40.2,29.7,7.8,8.6,12.0,3.2
2,34382,23.5,Alabama,57.5,40.7,11.0,12.1,19.7,4.5
3,46064,21.1,Alabama,51.6,38.7,8.6,10.0,14.1,3.3
4,50412,23.6,Alabama,46.3,34.0,9.2,10.5,13.5,3.4
...,...,...,...,...,...,...,...,...,...
3135,73315,15.8,Wyoming,40.3,33.6,5.9,6.6,8.9,2.6
3136,99087,18.7,Wyoming,24.3,19.4,5.2,4.9,7.2,2.4
3137,63401,17.1,Wyoming,42.2,34.2,7.2,8.0,10.4,3.0
3138,55190,26.7,Wyoming,37.5,28.4,8.2,8.3,11.3,3.4
3139,54319,29.1,Wyoming,46.0,34.4,8.5,8.7,11.7,3.4

In [8]:
total_data_gropued = total_data.groupby("STATE_NAME").mean()
total_data_gropued = total_data_gropued.reset_index()
total_data_gropued

,STATE_NAME,Median_Household_Income_2018,Percent of Population Aged 60+,anycondition_prevalence,Obesity_prevalence,Heart disease_prevalence,COPD_prevalence,diabetes_prevalence,CKD_prevalence
0,Alabama,43479.820896,23.861194,53.026866,38.273134,9.616418,10.679104,16.232836,3.858209
1,Alaska,64079.000000,17.985185,42.403704,32.048148,7.448148,8.188889,11.970370,3.181481
2,Arizona,49105.866667,26.046667,45.293333,32.160000,9.000000,8.940000,13.040000,3.973333
3,Arkansas,41801.373333,25.332000,50.680000,36.868000,10.230667,10.697333,14.882667,3.789333
4,California,67098.655172,23.184483,38.218966,27.813793,6.901724,6.922414,11.325862,3.246552
5,Colorado,59599.671875,25.273438,35.179688,25.365625,6.976562,6.676563,9.768750,3.154688
6,Connecticut,77438.625000,23.025000,36.225000,27.475000,6.312500,6.262500,9.575000,2.725000
7,Delaware,61454.333333,24.933333,45.200000,36.000000,7.666667,8.166667,12.866667,3.300000
8,District of Columbia,82533.000000,16.800000,32.000000,24.800000,4.100000,4.900000,8.100000,2.600000
9,Florida,50621.104478,27.462687,46.925373,32.949254,9.598507,10.382090,13.905970,3.711940
10,Georgia,47507.081761,22.419497,47.933962,35.077987,8.625786,9.866667,15.084906,3.728931
11,Hawaii,58512.400000,25.740000,37.600000,24.640000,7.660000,6.020000,12.240000,3.540000
12,Idaho,52215.750000,24.806818,42.093182,31.752273,8.175000,7.913636,12.313636,3.381818
13,Illinois,56225.823529,24.828431,46.694118,34.231373,8.043137,9.021569,11.438235,3.250980
14,Indiana,56036.184783,23.028261,46.793478,35.316304,8.095652,10.084783,12.916304,3.160870
15,Iowa,57229.626263,26.045455,44.863636,35.948485,7.881818,7.388889,10.980808,3.151515
16,Kansas,52188.780952,25.910476,47.354286,37.422857,8.315238,8.286667,12.735238,3.320000
17,Kentucky,45238.516667,23.142500,54.342500,39.550833,10.523333,13.150833,15.423333,3.635000
18,Louisiana,45023.656250,21.348437,51.839062,38.901562,9.095313,10.554688,15.107812,3.746875
19,Maine,51536.500000,28.281250,43.206250,31.362500,8.725000,8.962500,11.537500,3.356250
20,Maryland,75031.000000,22.729167,43.841667,33.529167,7.033333,7.500000,12.300000,3.058333
21,Massachusetts,75312.785714,24.057143,36.021429,26.735714,6.528571,6.235714,9.307143,2.821429
22,Michigan,51601.373494,27.875904,47.633735,35.398795,9.366265,10.312048,12.531325,3.503614
23,Minnesota,60664.321839,25.512644,42.009195,33.466667,7.397701,6.224138,10.452874,3.094253
24,Mississippi,39932.719512,22.053659,54.503659,40.997561,9.301220,10.347561,16.304878,3.939024
25,Missouri,46770.191304,25.147826,48.602609,35.426957,9.109565,10.609565,12.953043,3.439130
26,Montana,49370.214286,28.467857,40.748214,31.130357,8.539286,7.953571,11.883929,3.464286
27,Nebraska,53588.849462,27.933333,45.321505,36.497849,8.133333,7.590323,11.397849,3.284946
28,Nevada,60823.647059,26.223529,47.005882,32.035294,8.805882,9.288235,12.470588,3.458824
29,New Hampshire,67052.600000,26.030000,40.210000,29.800000,7.230000,8.210000,10.760000,2.900000
30,New Jersey,81475.809524,22.033333,38.109524,29.209524,6.614286,6.414286,11.052381,2.909524
31,New Mexico,43713.303030,26.554545,45.481818,32.651515,8.663636,7.963636,14.442424,4.009091
32,New York,60891.822581,23.825806,42.630645,32.130645,7.654839,8.566129,11.511290,3.117742
33,North Carolina,48691.640000,25.371000,47.919000,35.051000,9.063000,9.645000,14.175000,3.692000
34,North Dakota,58070.301887,27.232075,46.456604,35.735849,8.601887,7.400000,11.833962,3.294340
35,Ohio,55374.965909,23.623864,48.664773,36.570455,8.626136,9.971591,12.854545,3.209091
36,Oklahoma,47492.000000,23.600000,50.316883,36.802597,9.620779,9.961039,13.841558,3.571429
37,Oregon,54679.472222,28.544444,44.250000,32.372222,8.713889,8.952778,12.552778,3.508333
38,Pennsylvania,55861.895522,25.865672,44.804478,33.385075,8.031343,8.555224,11.901493,3.213433
39,Rhode Island,73987.200000,24.860000,36.540000,26.860000,6.820000,7.120000,10.060000,2.800000
40,South Carolina,46011.826087,24.639130,49.719565,37.476087,8.580435,9.165217,15.441304,3.815217
41,South Dakota,51945.212121,25.431818,44.040909,33.818182,8.680303,7.110606,11.837879,3.440909
42,Tennessee,47251.452632,24.809474,51.256842,36.644211,9.730526,11.753684,14.528421,3.588421
43,Texas,51302.248031,23.405118,49.285433,37.330315,8.795669,8.341732,14.409843,3.594094
44,Utah,62675.172414,19.324138,39.227586,30.889655,6.403448,6.031034,10.317241,2.893103
45,Vermont,58226.428571,26.750000,37.100000,28.142857,7.078571,7.478571,10.007143,2.985714
46,Virginia,59157.676692,24.911278,45.647368,33.987970,8.139098,8.624060,12.840602,3.382707
47,Washington,59598.179487,26.492308,40.794872,31.633333,7.874359,7.369231,11.515385,3.315385
48,West Virginia,43184.236364,26.998182,55.930909,39.083636,11.181818,13.781818,15.838182,3.698182
49,Wisconsin,58008.750000,25.975000,42.844444,34.770833,7.795833,7.358333,10.600000,3.204167
50,Wyoming,61964.434783,23.839130,38.947826,30.043478,7.321739,7.600000,10.226087,3.047826

In [9]:
total_data_gropued.to_csv('/workspaces/EDA_4/data/processed/conditions_per_state.csv', index= False)